site_name: pytorch-doc-cn
pages:
    - 主页: index.md
    - torchvision: torchvision.md
    - torchvision-datasets: torchvision-datasets.md
    - torchvision-models: torchvision-models.md
    - torchvision-transform: torchvision-transform.md
    - torchvision-util: torchvision-utils.md
